version: 2
updates:
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      riverpod:
        patterns:
          - 'hooks_riverpod'
          - 'riverpod_annotation'
          - 'riverpod_generator'
          - 'flutter_hooks'
      graphql:
        patterns:
          - 'graphql_flutter'
          - 'graphql_codegen'
          - 'gql'
      codegen:
        patterns:
          - 'build_runner'
          - 'json_serializable'
          - 'json_annotation'

  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
