include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_specify_types: true
    prefer_single_quotes: true

analyzer:
  exclude:
    - '**/*.g.dart'
    - 'lib/graphql/*.graphql.dart'
