name: tokenzyme_mobile
description: 'Mobile client for Tokenzyme, a permissionless token launchpad for EVM chains.'
version: 1.0.1+2

repository: https://github.com/tokenzyme/tokenzyme-mobile
issue_tracker: https://github.com/tokenzyme/tokenzyme-mobile/issues

publish_to: 'none'

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  awesome_extensions: 2.0.25
  decimal: 3.2.4
  flutter_dotenv: 5.2.1
  flutter_hooks: 0.20.5
  flutter_native_splash: 2.4.6
  flutter_secure_storage: 9.2.4
  gql: 1.0.1-alpha+1730759315362
  graphql_flutter: 5.2.0
  hooks_riverpod: 2.6.1
  http: 1.5.0
  hugeicons: 1.1.7
  image_picker: 1.2.0
  intl: 0.20.2
  json_annotation: 4.9.0
  package_info_plus: 8.3.1
  reown_appkit: 1.6.0
  riverpod_annotation: 2.6.1
  shared_preferences: 2.5.3
  sliver_tools: 0.2.12
  socket_io_client: 3.1.2
  timeago: 3.7.1
  top_snackbar_flutter: 3.3.0
  url_launcher: 6.3.2
  web3dart: 2.7.3
  webview_flutter: 4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.5.4
  flutter_lints: 6.0.0
  graphql_codegen: 1.2.3
  json_serializable: 6.9.5
  riverpod_generator: 2.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/erc20_abi.json
    - assets/launchpad_abi.json
    - assets/splash.png
    - .env
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700

flutter_native_splash:
  ios: true
  android: true
  android_12:
    color: '#000000'
    image: 'assets/splash.png'
  color: '#000000'
  image: 'assets/splash.png'