type Account {
  address: String!
}

type SignInResult {
  account: Account!
  token: String!
}

type SignatureMessage {
  id: String!
  message: String!
}

type Comment {
  id: Int!
  accountAddress: String!
  text: String!
  createdAt: DateTime!
}

"""
A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
"""
scalar DateTime

type SocialMedia {
  xUrl: String
  telegramUrl: String
  discordUrl: String
  redditUrl: String
  facebookUrl: String
  instagramUrl: String
}

type Token {
  address: String!
  creatorAddress: String!
  name: String!
  symbol: String!
  description: String!
  logoUrl: String!
  websiteUrl: String
  totalSupply: Decimal!
  bondingCurveSupply: Decimal!
  ethReserve: Decimal!
  reserve: Decimal!
  price: Decimal!
  finalPrice: Decimal!
  dexPoolAddress: String
  migratedAt: DateTime
  createdAt: DateTime!
  socialMedia: SocialMedia
  tradesCount: Int!
  commentsCount: Int!
}

"""Decimal value as a number"""
scalar Decimal

type TopHolder {
  accountAddress: String!
  balance: Decimal!
  percentage: Float!
}

type UploadSignedUrl {
  uploadUrl: String!
  cdnUrl: String!
}

type TradeCandle {
  time: Float!
  open: Decimal!
  high: Decimal!
  low: Decimal!
  close: Decimal!
  volume: Decimal!
}

type Trade {
  id: String!
  accountAddress: String!
  type: TradeType!
  tokenAmount: Decimal!
  ethAmount: Decimal!
  createdAt: DateTime!
}

enum TradeType {
  BUY
  SELL
}

type Query {
  comments(tokenAddress: String!, pageSize: Int!, lastCommentId: Int): [Comment!]!
  ethPrice: Float!
  tokenLogoUploadUrl: UploadSignedUrl!
  tokens(sortType: TokenSortType!, pageSize: Int, lastTokenAddress: String): [Token!]!
  firstPromotedTokensOfMonth: [Token!]!
  isTokenRegistered(address: String!): Boolean!
  token(address: String!): Token!
  topHolders(tokenAddress: String!): [TopHolder!]!
  trades(tokenAddress: String!, pageSize: Int!, lastTradeId: String): [Trade!]!
  tradeCandles(tokenAddress: String!, resolution: String!, pageSize: Int!, lastCandleTimestamp: Float): [TradeCandle!]!
}

enum TokenSortType {
  NEW
  PROGRESS
  PROMOTED
}

type Mutation {
  signIn(input: SignInInput!): SignInResult!
  createSignatureMessage(input: CreateSignatureMessageInput!): SignatureMessage!
  addComment(input: AddCommentInput!): Comment!
}

input SignInInput {
  signatureMessageId: String!
  signature: String!
}

input CreateSignatureMessageInput {
  accountAddress: String!
  type: SignatureMessageType!
}

enum SignatureMessageType {
  SIGN_IN
}

input AddCommentInput {
  tokenAddress: String!
  text: String!
}